version: '3.8'

services:
  app:
    image: automatches-app  # Replace this with your actual Node.js app image
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - C:/GenerationFootball/automatches:/app
      - C:/GenerationFootball/data:/app/data
      - C:/GenerationFootball/data/leagues:/app/data/leagues
      - C:/GenerationFootball/data/matches:/app/data/matches
    networks:
      - caddy_network
    restart: always  # To ensure your app restarts if it crashes

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:8443"
      - "8443:8443"     # Additional HTTPS port
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - ACME_AGREE=true
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    networks:
      - caddy_network
    restart: always

networks:
  caddy_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
